version: '3.3'

services:
  db2:
    image: ibmcom/db2:11.5.0.0
    container_name: db2-db
    ports:
      - 50000:50000
    volumes:
      - ~/apps/db2:/database
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=example
      - DBNAME=FOO_DB
    command: db2start


# docker run -itd --name db2 --privileged=true -p 50000:50000 -e LICENSE=accept -e DB2INST1_PASSWORD=db2inst1 -e DBNAME=test -v /home/ubuntu/DB2:/database ibmcom/db2

# sudo docker exec -i -t db2 /bin/bash

# su - db2inst1

# db2start

# db2 

# LIST DATABASE DIRECTORY

# create database test 

# connect to test user db2inst1 using db2inst1 

# list tables

# CREATE TABLE principal_table (id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name VARCHAR(100) NOT NULL, description VARCHAR(255))
# CREATE TABLE secondary_table_1 (id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, principal_id INT NOT NULL, value VARCHAR(100) NOT NULL, FOREIGN KEY (principal_id) REFERENCES principal_table (id))
# CREATE TABLE secondary_table_2 (id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, principal_id INT NOT NULL, details VARCHAR(255), FOREIGN KEY (principal_id) REFERENCES principal_table (id))

# INSERT INTO principal_table (name, description) VALUES ('Principal Record 1', 'This is the main record')
# INSERT INTO secondary_table_1 (principal_id, value) VALUES (1, 'Secondary 1 Value')
# INSERT INTO secondary_table_2 (principal_id, details) VALUES (1, 'Details for Secondary 2')

# SELECT * FROM PRINCIPAL_TABLE

CREATE TABLE TEST_TABLE (ID SMALLINT NOT NULL PRIMARY KEY, QUANTITY INTEGER NOT NULL, LARGE_NUMBER BIGINT NOT NULL, PRICE DECIMAL(10, 2) NOT NULL, TRANSACTION_DATE DATE NOT NULL, LAST_UPDATED TIMESTAMP NOT NULL)
INSERT INTO TEST_TABLE (ID, QUANTITY, LARGE_NUMBER, PRICE, TRANSACTION_DATE, LAST_UPDATED) VALUES (1, 100, 123456789012345, 99.99, '2025-01-12', CURRENT TIMESTAMP), (2, 200, 987654321098765, 199.49, '2025-01-11', CURRENT TIMESTAMP), (3, 300, 123456789012345, 299.99, '2025-01-10', CURRENT TIMESTAMP)



SELECT fk.tabname AS table_name, fk.colname AS column_name FROM syscat.keycoluse fk JOIN syscat.keycoluse pk ON fk.constname = pk.constname JOIN syscat.tabconst tc ON pk.constname = tc.constname WHERE tc.enforced = 'Y' AND pk.tabname = 'PRINCIPAL_TABLE' AND pk.colname = 'ID' AND fk.tabname <> pk.tabname


SELECT fk.tabname AS table_name, fk.colname AS column_name FROM syscat.keycoluse fk JOIN syscat.tabconst tc ON fk.constname = tc.constname WHERE tc.enforced = 'Y' AND tc.type = 'F' AND tc.tabname = 'PRINCIPAL_TABLE' AND tc.tabname = 'ID'

CREATE TABLE DB2MCO.TMCO_TESTE (COD_ITEM INTEGER NOT NULL, DTA_INIC_VIGN DATE NOT NULL, COD_UNID_MEDI SMALLINT NOT NULL, IDC_AJUS_CSTO DECIMAL(6,5) NOT NULL, COD_INSU_BCEN CHAR(8), IND_ITEM_ACTO_GRNT DECIMAL(1,0) NOT NULL, COD_TIPO_MOED SMALLINT NOT NULL, COD_TIPO_ITEM_ORCM SMALLINT NOT NULL, COD_ALIQ_PNHO_RURL SMALLINT, COD_ITEM_FINC INTEGER, DTA_FIM_VIGN DATE, CHV_USUR CHAR(8) NOT NULL, "TIMESTAMP" TIMESTAMP NOT NULL, NOM_ITEM_ORCM VARCHAR(60) NOT NULL, CD_TIP_DSP SMALLINT, PRIMARY KEY (COD_ITEM, DTA_INIC_VIGN))

INSERT INTO DB2MCO.TMCO_TESTE (COD_ITEM, DTA_INIC_VIGN, COD_UNID_MEDI, IDC_AJUS_CSTO, COD_INSU_BCEN, IND_ITEM_ACTO_GRNT, COD_TIPO_MOED, COD_TIPO_ITEM_ORCM, COD_ALIQ_PNHO_RURL, COD_ITEM_FINC, DTA_FIM_VIGN, CHV_USUR, "TIMESTAMP", NOM_ITEM_ORCM, CD_TIP_DSP) VALUES (1, '2023-01-01', 1, 1.00000, 'BCEN1234', 1, 1, 1, 1, 1, '2023-12-31', 'USER1234',CURRENT_TIMESTAMP, 'Item de Orçamento 1', 1)
INSERT INTO DB2MCO.TMCO_TESTE (COD_ITEM, DTA_INIC_VIGN, COD_UNID_MEDI, IDC_AJUS_CSTO, COD_INSU_BCEN, IND_ITEM_ACTO_GRNT, COD_TIPO_MOED, COD_TIPO_ITEM_ORCM, COD_ALIQ_PNHO_RURL, COD_ITEM_FINC, DTA_FIM_VIGN, CHV_USUR, "TIMESTAMP", NOM_ITEM_ORCM, CD_TIP_DSP) VALUES (2, '2023-01-01', 2, 2.00000, 'BCEN5678', 1, 2, 2, 2, 2, '2023-12-31', 'USER5678', CURRENT_TIMESTAMP, 'Item de Orçamento 2', 2)
